import type { Analyzer, AnalyzerFinding } from './types'
import { looksGenerated } from './support'

const HUGE_LOC = 800
const LARGE_ASSET_BYTES = 5 * 1024 * 1024

/** Flags unmaintainably large source files and oversized committed assets. */
export const sizeAnalyzer: Analyzer = {
  id: 'size',
  name: 'File Size',
  description: 'Detects oversized source files and large binary assets committed to the repo.',
  async run(index) {
    const findings: AnalyzerFinding[] = []

    for (const f of index.files) {
      if (f.loc > HUGE_LOC && (f.kind === 'source' || f.kind === 'component' || f.kind === 'route')) {
        if (f.content && looksGenerated(f.content)) {
          // Machine-written files don't get hand-refactoring advice — the
          // actionable observation is that a build artifact is committed.
          findings.push({
            category: 'STRUCTURE',
            severity: 'LOW',
            title: `Generated artifact committed: ${f.path.split('/').pop()} (${f.loc} LOC)`,
            description: `${f.path} declares itself autogenerated. Large generated files bloat diffs and invite accidental hand-edits.`,
            filePath: f.path,
            suggestion: 'Generate it at build time instead of committing it, or mark it linguist-generated in .gitattributes.',
            impactScore: 25,
            effort: 'low',
            metadata: { loc: f.loc, generated: true },
          })
          continue
        }
        findings.push({
          category: 'TECH_DEBT',
          severity: f.loc > 2000 ? 'HIGH' : 'MEDIUM',
          title: `Oversized file: ${f.path.split('/').pop()} (${f.loc} LOC)`,
          description: `${f.path} has ${f.loc} lines of code. Files this large are hard to review, test, and safely change.`,
          filePath: f.path,
          suggestion: 'Split into focused modules along responsibility boundaries.',
          impactScore: Math.min(90, 40 + Math.floor(f.loc / 100)),
          effort: 'medium',
          metadata: { loc: f.loc },
        })
      }
      if (f.kind === 'asset' && f.sizeBytes > LARGE_ASSET_BYTES) {
        findings.push({
          category: 'STRUCTURE',
          severity: 'LOW',
          title: `Large asset committed: ${f.path.split('/').pop()}`,
          description: `${f.path} is ${(f.sizeBytes / 1024 / 1024).toFixed(1)} MB. Large binaries bloat clones and slow CI.`,
          filePath: f.path,
          suggestion: 'Move large assets to object storage or Git LFS.',
          impactScore: 25,
          effort: 'low',
        })
      }
    }
    return findings
  },
}
