/** Shared constants required by deterministic analyzers. */
export const SUPPORTED_TREESITTER_LANGS: readonly string[] = ['c#', 'go', 'java', 'rust', 'php', 'ruby']
export const SAST_COVERED_LANGUAGES: ReadonlySet<string> = new Set(['TypeScript', 'JavaScript', 'Python'])
export function looksGenerated(content: string): boolean {
  const head = content.split('\n', 5).join('\n')
  return /auto-?generated|@generated|generated by|do not edit/i.test(head)
}
